# molecule
dataset:
  molecule: Alanine Dipeptide
  name: Ala2TSF300
  save_image: True

model:
  prior: normal
  type: nvp
  hidden_dim: [128, 128, 128]
  layers: 12
  lr: 5e-2

train:
  loss: kll
  iter: 5000
  batchsize: 1024
  n_print: 500
  w_energy: 0.0

sample:
  n_samples: 100000

path: ./result

plot:
  distribution: True
  energy: True
  hist2d: 100
  hist: 50

wandb:
  project: cv
  entity: eddy26