# molecule
dataset:
  molecule: Alanine Dipeptide
  name: Ala2TSF300
  save_image: True

model:
  prior: normal
  type: nvp
  hidden_dim: [128, 128, 128]
  layers: 5
  lr: 1e-3

train:
  loss: nll
  iter: 200000
  batchsize: 128
  n_print: 1000
  w_energy: 0.0

sample:
  n_samples: 10000

path: ./result
