# molecule
dataset:
  molecule: Alanine Dipeptide
  name: Ala2TSF300
  save_image: True

model:
  type: nvp
  layers: 5
  lr: 1e-4

train:
  loss: mixed
  iter: 20000
  batchsize: 1000
  n_print: 1000
  w_energy: 0.1
  w_likelihood: 0.9
  clip_forces: 20.0

sample:
  n_samples: 10000

path: ./result

wandb:
  project: cv
  entity: eddy26